version: "1"
rules:
  - base: bdw-dev
    upstream: master
    mergeMethod: merge
    assignees:
      - skulegirl
  - base: master
    upstream: psychok7:master
    mergeMethod: hardreset
    mergeUnstable: true
    conflictReviewers:
      - skulegirl
