# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_backends', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='medium',
            field=models.CharField(choices=[(0, 'email')], max_length=100, verbose_name='medium'),
        ),
    ]
