# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-07 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_backends', '0002_auto_20170531_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='medium',
            field=models.CharField(choices=[(0, 'email'), (1, 'sms')], max_length=100, verbose_name='medium'),
        ),
    ]
