# Generated by Django 2.2.16 on 2020-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_backends', '0003_auto_20180207_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='medium',
            field=models.CharField(max_length=100, verbose_name='medium'),
        ),
    ]
