# Generated by Django 2.2.16 on 2020-09-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_backends', '0004_auto_20200918_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='exception',
            field=models.BooleanField(default=False, verbose_name='exception'),
        ),
    ]
